INSERT INTO TODO (ID,DESCRIPTION,DONE,TARGET_DATE,USERNAME)
VALUES (10001,'Learn English',false,CURRENT_DATE(),'ashraf');

INSERT INTO TODO (ID,DESCRIPTION,DONE,TARGET_DATE,USERNAME)
VALUES (10002,'Learn French',false,CURRENT_DATE(),'ashraf');

INSERT INTO TODO (ID,DESCRIPTION,DONE,TARGET_DATE,USERNAME)
VALUES (10003,'Learn Japanese',false,CURRENT_DATE(),'ashraf');