INSERT INTO USER_DETAILS (BIRTH_DATE,ID,NAME) VALUES ('2001-08-04',10,'Ashraf');

INSERT INTO POSTS (ID,USER_ID,DESCRIPTION) VALUES(1001,10,'Hello bro');
INSERT INTO POSTS (ID,USER_ID,DESCRIPTION) VALUES(1002,10,'Hi bro');